inherit_from: .rubocop_todo.yml

Metrics/BlockLength:
  Enabled: true

Metrics/ClassLength:
  Enabled: true

Metrics/ModuleLength:
  Enabled: true

Layout:
  Enabled: true

Metrics/MethodLength:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/GuardClause:
    Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 160

# Metrics/MethodLength:
#   Max: 90

# Metrics/ClassLength:
#   Max: 1000

# Lint/EndAlignment:
#   AutoCorrect: true

# Style/HashEachMethods:
#   Enabled: true

# Style/HashTransformKeys:
#   Enabled: true

# Style/HashTransformValues:
#   Enabled: true


AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'